# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `lzfse` gem.
# Please instead update this file by running `bin/tapioca gem lzfse`.

# The main module for *lzfse.rb*.
#
# source://lzfse//lib/lzfse/exceptions.rb#3
module LZFSE
  private

  # source://lzfse//lib/lzfse.rb#10
  def lzfse_compress(string); end

  # source://lzfse//lib/lzfse.rb#14
  def lzfse_decompress(string); end

  # source://lzfse//lib/lzfse.rb#18
  def lzvn_compress(string); end

  # source://lzfse//lib/lzfse.rb#22
  def lzvn_decompress(string); end

  class << self
    # source://lzfse//lib/lzfse.rb#10
    def lzfse_compress(string); end

    def lzfse_decode_intern(_arg0); end

    # source://lzfse//lib/lzfse.rb#14
    def lzfse_decompress(string); end

    def lzfse_encode_intern(_arg0); end

    # source://lzfse//lib/lzfse.rb#18
    def lzvn_compress(string); end

    def lzvn_decode_intern(_arg0); end

    # source://lzfse//lib/lzfse.rb#22
    def lzvn_decompress(string); end

    def lzvn_encode_intern(_arg0); end
  end
end

# source://lzfse//lib/lzfse/exceptions.rb#10
class LZFSE::DecodeError < ::LZFSE::LZFSEError; end

# source://lzfse//lib/lzfse/exceptions.rb#7
class LZFSE::EncodeError < ::LZFSE::LZFSEError; end

# source://lzfse//lib/lzfse/exceptions.rb#4
class LZFSE::LZFSEError < ::RuntimeError; end
