# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-lzma` gem.
# Please instead update this file by running `bin/tapioca gem ruby-lzma`.

# source://ruby-lzma//lib/lzma.rb#25
class LZMA
  def compress(_arg0); end
  def decompress(_arg0); end

  class << self
    # source://ruby-lzma//lib/lzma.rb#29
    def compress(data); end

    # source://ruby-lzma//lib/lzma.rb#26
    def decompress(data); end
  end
end
