plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable

RSpec/SpecFilePathFormat:
  Enabled: true
  CustomTransform:
    MooTool: mootool

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 35

Style/Documentation:
  Exclude:
    - 'lib/mootool/config/initializers/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 25

Metrics/ModuleLength:
  Max: 200