plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - 'docs/**'

RSpec/SpecFilePathFormat:
  Enabled: true
  CustomTransform:
    MooTool: mootool

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Style/Documentation:
  Exclude:
    - 'lib/mootool/config/initializers/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 50

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5